### ISSUE TITLE
Silenced shot exploit

### ISSUE THREAD

**Issue by goatwithakb** [xDShot/csgo_knives_sweps#7]
Firing a weapon then quickswitching to a knife will silence the remainder of the gunshot.

I think it's because of the custom knife sounds implemented.

**Comment by xDShot** [comment]
This is a pure cosmetic issue. That's because knife deploy sound is assigned on `CHAN_WEAPON` channel where are firing sounds as well. Since deploy sound is played on first person model only, it's not hearable in third person (by some one other) and doesn't really interrupt any firing, so it can't be exploited.

**Comment by goatwithakb** [comment]
Thanks for the speedy reply.

Also thanks for making this open source, I used one of your earlier commits to add one knife to T-shop for TTT, and it's working very well for our server :)
